name: test

on: [push]

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: dependencies
        run: |
          git clone https://github.com/0xevm/foundry.git
          cd foundry
          git checkout beijing-eth
          cargo build --release -p foundry-cli --bin forge
      - name: Run Forge build
        run: |
          ./foundry/target/release/forge --version
          ./foundry/target/release/forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          ./foundry/target/release/forge test -vvv
        id: test
